# Generated by Django 4.0.4 on 2022-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=500)),
                ('Members', models.CharField(max_length=500)),
                ('member1', models.CharField(max_length=500)),
                ('member2', models.CharField(max_length=500)),
                ('member3', models.CharField(max_length=500)),
                ('member4', models.CharField(max_length=500)),
                ('member5', models.CharField(max_length=500)),
                ('member6', models.CharField(max_length=500)),
                ('member7', models.CharField(max_length=500)),
                ('tendays', models.CharField(max_length=500)),
                ('twentydays', models.CharField(max_length=500)),
                ('thirtydays', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=100),
        ),
    ]
